package com.dev.vault.AuthenticationService.model.entity.jwt;

import com.dev.vault.AuthenticationService.model.entity.User;
import jakarta.persistence.*;
import lombok.*;

/**
 * Entity for saving JWT token that has been generated by registration and or authentication/login.
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name = "jwt_token")
public class JwtToken {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long jwtTokenId;

    private String token;
    @Enumerated(EnumType.STRING)
    private TokenType type;
    private boolean expired;
    private boolean revoked;

    /* relationships */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
    /* end of relationships */

}
